package hayride:runners@0.0.1;

world cli {
    include hayride:wasip2/imports@0.0.55;
    include hayride:wasip2/exports@0.0.55;
    
    import hayride:ai/agents@0.0.55;
    import hayride:ai/model-repository@0.0.55;
    import hayride:ai/graph-stream@0.0.55;
}

world http {
    include hayride:wasip2/imports@0.0.55;
    export wasi:http/incoming-handler@0.2.0;
   
    import hayride:ai/agents@0.0.55;
    import hayride:ai/graph-stream@0.0.55;

}