package hayride:runners@0.0.1;

world cli {
    include hayride:wasip2/imports@0.0.44;
    include hayride:wasip2/exports@0.0.44;
    
    import hayride:ai/agent@0.0.44;
}

world http {
    include hayride:wasip2/imports@0.0.44;
    export wasi:http/incoming-handler@0.2.0;
   
    import hayride:ai/agent@0.0.44;
}