package hayride:agents@0.0.1;

world agent {
    include hayride:wasip2/imports@0.0.42;
    import hayride:ai/context@0.0.42;
    import hayride:ai/model@0.0.42;
    import hayride:ai/graph-stream@0.0.42;

    import hayride:datetime/datetime@0.0.1;

    export hayride:ai/agent@0.0.42;
}